name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ZacJW/markdown-html-action@1.1.1
        with:
          input_files: '[["docs/EULA.md"]]'
          output_files: '["output/EULA.html"]'          
      - name: Push to legal text consumer
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.KADDASZ_ACCESS_TOKEN }}
            DEST_GITHUB_USERNAME: 'kaddaSz'
            DEST_REPO_NAME: 'cwa-legal-texts-consumer'
            USER_EMAIL: 'katharina.seiz@sap.com'
            PUSH_TO_BRANCH: 'legal/html-files'
            PR_TO_BRANCH: 'main'
            SRC_DIR: 'output/*'
            PR_MESSAGE: 'Legal Text updates'
